[AccountPasswordUpdateAction]
update = "Le mot de passe a été mis à jour."
wrongOldPassword = "L'ancien mot de passe ne correspond pas."
wrongPasswordVerify = "La vérification du mot de passe ne correspond pas."

[AccountUpdateAction]
update = "Vos informations ont été mis à jour."

[Auth]
errorPassword = "Mot de passe incorrect."
errorUserNotExists = "Cet utilisateur n'existe pas."

[LogoutAction]
offline = "Vous êtes déconnecté."

[PermissionAddRoleAction]
associationSuccess = "Le rôle a été associé à la permission."
notExists = "Cette permission n'existe pas."
rolePermissionExists = "Cette relation entre ce rôle et cette permission existe déjà."

[PermissionDeleteRoleAction]
deleteSuccess = "L'association entre le rôle et la permission a été supprimée."