[AccountPasswordUpdateAction]
update = "The password has been updated."
wrongOldPassword = "Old password does not match."
wrongPasswordVerify = "Password verification does not match."

[AccountUpdateAction]
update = "yours informations has been updated."

[Auth]
errorPassword = "Incorrect password."
errorUserNotExists = "This user does not exists."

[ForbiddenMiddleware]
errorNotConnected = "You need to be connected to acces to this page."
errorNotPermission = "You do not have the permissions to access this page."

[LogoutAction]
offline = "You are now offline."

[PermissionAddRoleAction]
associationSuccess = "Role has been associated with permission."
notExists = "This permission does not exists."
rolePermissionExists = "This relation between this role and this permission already exists."

[PermissionDeleteRoleAction]
deleteSuccess = "The association between the role and the permission is deleted."